version: "3.9"

services:
  backend:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_ADDR=redis:6379

  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  redis:
    driver: local
  postgres:
    driver: local
